project:
  type: website

website:
  title: "BSTT 537: Longitudinal Analysis"
  navbar:
    left:
      - index.qmd
      - lectures.qmd
      - homework.qmd
      - notes.qmd

format:
  html:
    theme: cosmo

execute:
  freeze: auto

